[pytest]
testpaths =
    tests
    trading_system/tests
    coinbase/tests
    event_markets
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = -p no:cacheprovider
filterwarnings =
    ignore::DeprecationWarning
