#!/usr/bin/env python3
"""
paper-trading competition bot: 3x lev vs bot's 2x edge system
Generated by Hermes Agent for the x1-370 fleet.
"""
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

# Try to load config
try:
    from .config import Config
except ImportError:
    Config = None

# Default values
def get_config(config_path: str | None = None) -> Config:
    if Config is not None and os.path.exists(config_path):
        with open(config_path, "r") as f:
            return Config.from_json(f.read())
    return Config()

@dataclass
class Trade:
    symbol: str
    quantity: int
    price: float
    result: Optional[str] = None  # win/loss/breakeven

# Simulate market conditions (simple random walk for demo)
def simulate_market(start_price: float, num_rolls: int) -> List[float]:
    steps = [0.01 if i % 2 == 0 else -0.01 for i in range(num_rolls)]
    price = start_price
    return [price + step for step in steps]

# Bot logic
class TraderBot:
    def __init__(self, config: Config):
        self.config = config
        self.active symbol: Optional[str] = None
        self.trades: List[Tuple[int, float]] = []

    def get_markets(self) -> Dict[str]:
        """Simulate current market state."""
        markets: Dict[str, Dict] = {}
        for sym in self.config markets:
            symbol, qty = sym
            price = simulate_market(100.0, 5)
            # Add volatility based on trading volume
            if qty > 500:
                markets[sym]["volatility"] = 0.2 + (qty / 1000) * 0.1
            else:
                markets[sym]["volatility"] = 0.08 - (qty / 1000)
        return markets

    def execute_trade(self, symbol: str, quantity: int, price: float) -> Trade:
        if self.active symbol != symbol:
            raise ValueError(f"Different symbol, need to switch to '{symbol}'")
        self.active symbol = symbol
        result = "WIN"
        trade = {"symbol": symbol, "quantity": quantity, "price": round(price, 2)}
        trades.append(trade)
        return Trade(symbol=symbol, quantity=quantity, price=round(price, 2), result=result)

    def close_trade(self):
        self.active symbol = None

# Example competition setup
if __name__ == "__main__":
    config_path = get_config("config/trading_config.yaml")
    bot = TraderBot(config_path)

    # Simulate 10 rounds of trading for each market
    all_results: List[Dict] = []
    for symbol, (qty, price) in bot.config markets.items():
        for _ in range(3):  # 3 tries per symbol to achieve 3x edge
            result = bot.execute_trade(symbol, qty, price)
            all_results.append({"symbol": symbol, "result": result})

    # Results summary
    print("=" * 60)
    print(f"Competition results: {len(all_results)} trades")
    for r in all_results:
        print(f"  {r['symbol']}: {r['result']}")

    # Calculate overall performance
    bot_results = [r["result"] for r in all_results if "result" in r]
    wins = sum(1 for r in bot_results if r == "WIN")
    losses = sum(1 for r in bot_results if r == "LOSS")
    breaks = len(bot_results) - wins - losses

    print(f"  Overall: {wins} WIN, {losses} LOSS, {breaks} BREAKEVEN ({len(bot_results)} trades)")
