CREATE CONSTRAINT ticker_sym IF NOT EXISTS FOR (t:Ticker) REQUIRE t.symbol IS UNIQUE;
CREATE CONSTRAINT bar_key IF NOT EXISTS FOR (b:PriceBar) REQUIRE (b.symbol, b.date) IS UNIQUE;
CREATE CONSTRAINT strategy_name IF NOT EXISTS FOR (s:Strategy) REQUIRE s.name IS UNIQUE;
CREATE CONSTRAINT signal_id IF NOT EXISTS FOR (g:Signal) REQUIRE g.id IS UNIQUE;
CREATE CONSTRAINT acct_id IF NOT EXISTS FOR (a:BrokerAccount) REQUIRE a.id IS UNIQUE;
