"""Canonical historical replay and dataset attestation for alpha evidence.

This module closes the local data-origin gap between the durable feed cache and
``scripts.alpha_validation``.  It deliberately does not place orders or talk to
a broker.  A replay attestation is derived from the exact normalized candle
rows consumed by the Rust strategy evaluator, and verification reloads the same
time-bounded snapshot from ``data.feed_cache`` and replays it again.

Trust model
-----------
The attestation proves, relative to the checked-out code and the canonical local
feed cache, that:

* ``dataset_hash`` names the exact logical OHLCV rows replayed (not a
  caller-supplied label);
* every embedded OOS return was regenerated by the canonical Rust signal path;
* walk-forward boundaries and fee/holding assumptions are part of the hash;
* a later mutation of an in-range candle, replay setting, return, or runner
  source makes verification fail closed.

This is intentionally stronger than self-consistent JSON, but it is not a
remote hardware/CI signature.  A separate trusted-runner/immutable-store layer
can sign the deterministic attestation produced here.
"""
from __future__ import annotations

import hashlib
import math
from pathlib import Path
from typing import Any, Sequence

from data.feed_cache import load_candles
from scripts.alpha_validation import (
    build_alpha_validation_evidence,
    generate_walk_forward_splits,
    stable_hash,
    verify_alpha_validation_evidence,
)

ATTESTATION_SCHEMA_VERSION = 3
ATTESTATION_TYPE = "canonical_feed_cache_rust_replay_v3"
PARAMETER_STABILITY_METHOD = "rsi_one_at_a_time_log_growth_v1"
DATASET_KIND = "coinbase_candles"
RUNNER_ID = "scripts.backtest_framework.canonical_replay"
REQUIRED_RUST_SYMBOLS = (
    "run_strategy_opens_py",
    "run_rsi_revert_opens_configured_py",
    "backtest_strategy_py",
)
RSI_REVERT_CONFIG_KEYS = frozenset({"period", "oversold", "overbought"})


def canonical_rust_backend_available() -> bool:
    """Return True only for a compiled rust_core with replay-required exports."""

    try:
        import rust_core
    except ImportError:
        return False
    return all(callable(getattr(rust_core, name, None)) for name in REQUIRED_RUST_SYMBOLS)


def _require_rust_core():
    """Return the compiled backend or fail closed on namespace/stale modules."""

    try:
        import rust_core
    except ImportError as exc:
        raise RuntimeError("compiled rust_core is required for canonical replay") from exc
    missing = [
        name for name in REQUIRED_RUST_SYMBOLS
        if not callable(getattr(rust_core, name, None))
    ]
    if missing:
        raise RuntimeError(
            "compiled rust_core is missing required canonical replay symbols: "
            + ", ".join(missing)
        )
    return rust_core


def _runner_source_sha256() -> str:
    """Hash the exact replay implementation executing this attestation."""

    return hashlib.sha256(Path(__file__).read_bytes()).hexdigest()


def _finite_float(value: Any, *, name: str) -> float:
    try:
        result = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be numeric") from exc
    if not math.isfinite(result):
        raise ValueError(f"{name} must be finite")
    return result


def normalize_strategy_config(strategy_name: str, config: Any = None) -> dict[str, Any]:
    """Normalize the typed strategy parameters that canonical replay can execute."""
    if config is None or config == {}:
        return {}
    if not isinstance(config, dict):
        raise TypeError("strategy_config must be an object")
    if strategy_name != "rsi_revert":
        raise ValueError(f"configured canonical replay is not supported for {strategy_name!r}")
    if set(config) != RSI_REVERT_CONFIG_KEYS:
        missing = sorted(RSI_REVERT_CONFIG_KEYS - set(config))
        extra = sorted(set(config) - RSI_REVERT_CONFIG_KEYS)
        raise ValueError(f"rsi_revert strategy_config keys mismatch: missing={missing}, extra={extra}")
    period_number = _finite_float(config["period"], name="strategy_config.period")
    if isinstance(config["period"], bool) or not period_number.is_integer():
        raise ValueError("strategy_config.period must be an integer")
    period = int(period_number)
    oversold = _finite_float(config["oversold"], name="strategy_config.oversold")
    overbought = _finite_float(config["overbought"], name="strategy_config.overbought")
    if period < 2 or period > 200:
        raise ValueError("strategy_config.period must be in [2, 200]")
    if not (0.0 < oversold < overbought < 100.0):
        raise ValueError("strategy_config thresholds must satisfy 0 < oversold < overbought < 100")
    return {"period": period, "oversold": oversold, "overbought": overbought}


def rsi_parameter_neighbors(config: dict[str, Any]) -> list[dict[str, Any]]:
    """Return deterministic one-at-a-time neighbors for local robustness testing."""

    base = normalize_strategy_config("rsi_revert", config)
    specs = [
        ("period_minus_2", "period", max(2, base["period"] - 2)),
        ("period_plus_2", "period", min(200, base["period"] + 2)),
        ("oversold_minus_5", "oversold", base["oversold"] - 5.0),
        ("oversold_plus_5", "oversold", base["oversold"] + 5.0),
        ("overbought_minus_5", "overbought", base["overbought"] - 5.0),
        ("overbought_plus_5", "overbought", base["overbought"] + 5.0),
    ]
    out: list[dict[str, Any]] = []
    seen: set[str] = set()
    for label, key, value in specs:
        candidate = dict(base)
        candidate[key] = value
        try:
            normalized = normalize_strategy_config("rsi_revert", candidate)
        except (TypeError, ValueError):
            continue
        if normalized == base:
            continue
        config_hash = stable_hash(normalized)
        if config_hash in seen:
            continue
        seen.add(config_hash)
        out.append({"label": label, "config": normalized, "config_hash": config_hash})
    return out


def _fold_log_growth(fold_returns: Sequence[Sequence[Any]]) -> tuple[float, int]:
    growth = 0.0
    count = 0
    for fold_index, fold in enumerate(fold_returns):
        if not isinstance(fold, (list, tuple)):
            raise TypeError(f"fold_returns[{fold_index}] must be a sequence")
        for return_index, raw in enumerate(fold):
            value = _finite_float(raw, name=f"fold_returns[{fold_index}][{return_index}]")
            if value <= -1.0:
                raise ValueError("parameter-stability return cannot be <= -100%")
            growth += math.log1p(value)
            count += 1
    return growth, count


def _stability_summary(base_fold_returns: Sequence[Sequence[Any]], neighbors: Sequence[dict[str, Any]]) -> dict[str, Any]:
    base_log_growth, base_trade_count = _fold_log_growth(base_fold_returns)
    retentions: list[float] = []
    viable = 0
    normalized_rows: list[dict[str, Any]] = []
    for row in neighbors:
        fold_returns = row["fold_returns"]
        log_growth, trade_count = _fold_log_growth(fold_returns)
        profitable = trade_count > 0 and log_growth > 0.0
        if profitable:
            viable += 1
        retention = 0.0
        if profitable and base_log_growth > 0.0:
            retention = min(1.0, max(0.0, log_growth / base_log_growth))
        retentions.append(retention)
        normalized_rows.append({
            "label": row["label"],
            "config": row["config"],
            "config_hash": stable_hash(row["config"]),
            "fold_returns": fold_returns,
            "fold_returns_hash": stable_hash(fold_returns),
            "trade_count": trade_count,
            "log_growth": round(log_growth, 12),
            "profitable": profitable,
            "growth_retention": round(retention, 10),
        })
    count = len(normalized_rows)
    viable_fraction = viable / count if count else 0.0
    mean_retention = sum(retentions) / count if count else 0.0
    score = min(viable_fraction, mean_retention) if base_log_growth > 0.0 else 0.0
    return {
        "base_trade_count": base_trade_count,
        "base_log_growth": round(base_log_growth, 12),
        "neighbors": normalized_rows,
        "neighbor_count": count,
        "profitable_neighbor_count": viable,
        "profitable_neighbor_fraction": round(viable_fraction, 10),
        "mean_growth_retention": round(mean_retention, 10),
        "score": round(score, 10),
    }


def _build_parameter_stability_attestation(
    rows: Sequence[Sequence[Any]],
    boundaries: Sequence[Any],
    base_fold_returns: Sequence[Sequence[float]],
    *,
    strategy_config: dict[str, Any],
    warmup: int,
    fee_bps: float,
    max_hold_bars: int,
) -> dict[str, Any]:
    base = normalize_strategy_config("rsi_revert", strategy_config)
    neighbor_rows: list[dict[str, Any]] = []
    for spec in rsi_parameter_neighbors(base):
        fold_returns: list[list[float]] = []
        for boundary in boundaries:
            test_rows = rows[boundary.test_start:boundary.test_end]
            fold_returns.append(replay_trade_returns_rust(
                "rsi_revert",
                test_rows,
                warmup=warmup,
                fee_bps=fee_bps,
                max_hold_bars=max_hold_bars,
                strategy_config=spec["config"],
            ))
        neighbor_rows.append({**spec, "fold_returns": fold_returns})
    summary = _stability_summary(base_fold_returns, neighbor_rows)
    core = {
        "method": PARAMETER_STABILITY_METHOD,
        "base_config": base,
        "base_config_hash": stable_hash(base),
        "base_fold_returns_hash": stable_hash(base_fold_returns),
        **summary,
    }
    return {**core, "stability_hash": stable_hash(core)}


def _parameter_stability_reasons(
    payload: Any,
    *,
    base_config: dict[str, Any],
    base_fold_returns: Sequence[Sequence[float]],
) -> list[str]:
    if not isinstance(payload, dict):
        return ["replay_parameter_stability_missing"]
    required = {
        "method", "base_config", "base_config_hash", "base_fold_returns_hash",
        "base_trade_count", "base_log_growth", "neighbors", "neighbor_count",
        "profitable_neighbor_count", "profitable_neighbor_fraction",
        "mean_growth_retention", "score", "stability_hash",
    }
    missing = sorted(required - set(payload))
    if missing:
        return [f"replay_parameter_stability_missing_field:{name}" for name in missing]
    reasons: list[str] = []
    try:
        normalized_base = normalize_strategy_config("rsi_revert", base_config)
        if payload["method"] != PARAMETER_STABILITY_METHOD:
            reasons.append("replay_parameter_stability_method_mismatch")
        if payload["base_config"] != normalized_base:
            reasons.append("replay_parameter_stability_base_config_mismatch")
        if payload["base_config_hash"] != stable_hash(normalized_base):
            reasons.append("replay_parameter_stability_base_hash_mismatch")
        if payload["base_fold_returns_hash"] != stable_hash(base_fold_returns):
            reasons.append("replay_parameter_stability_base_returns_mismatch")
        expected_specs = rsi_parameter_neighbors(normalized_base)
        supplied_neighbors = payload["neighbors"]
        if not isinstance(supplied_neighbors, list) or len(supplied_neighbors) != len(expected_specs):
            reasons.append("replay_parameter_stability_neighbor_count_mismatch")
        else:
            raw_neighbors: list[dict[str, Any]] = []
            for index, (expected, supplied) in enumerate(zip(expected_specs, supplied_neighbors)):
                if not isinstance(supplied, dict):
                    reasons.append(f"replay_parameter_stability_neighbor_invalid:{index}")
                    continue
                if supplied.get("label") != expected["label"] or supplied.get("config") != expected["config"]:
                    reasons.append(f"replay_parameter_stability_neighbor_config_mismatch:{index}")
                    continue
                folds = supplied.get("fold_returns")
                if not isinstance(folds, list) or len(folds) != len(base_fold_returns):
                    reasons.append(f"replay_parameter_stability_neighbor_folds_mismatch:{index}")
                    continue
                raw_neighbors.append({
                    "label": expected["label"],
                    "config": expected["config"],
                    "fold_returns": folds,
                })
            if not reasons:
                expected_summary = _stability_summary(base_fold_returns, raw_neighbors)
                for name, expected_value in expected_summary.items():
                    if payload.get(name) != expected_value:
                        reasons.append(f"replay_parameter_stability_{name}_mismatch")
        core = dict(payload)
        supplied_hash = core.pop("stability_hash", None)
        if stable_hash(core) != supplied_hash:
            reasons.append("replay_parameter_stability_hash_mismatch")
    except (TypeError, ValueError, KeyError, OverflowError):
        reasons.append("replay_parameter_stability_invalid")
    return list(dict.fromkeys(reasons))


def normalize_candle_rows(rows: Sequence[Sequence[Any]]) -> list[list[float]]:
    """Canonicalize OHLCV rows and enforce replay-safe ordering/invariants."""

    out: list[list[float]] = []
    previous_ts: float | None = None
    for index, raw in enumerate(rows):
        if not isinstance(raw, (list, tuple)) or len(raw) < 6:
            raise ValueError(f"candle row {index} must contain t,o,h,l,c,v")
        row = [
            _finite_float(raw[column], name=f"row[{index}][{column}]")
            for column in range(6)
        ]
        ts, open_px, high_px, low_px, close_px, volume = row
        if previous_ts is not None and ts <= previous_ts:
            raise ValueError("candle timestamps must be strictly increasing")
        previous_ts = ts
        if min(open_px, high_px, low_px, close_px) <= 0.0:
            raise ValueError("candle prices must be positive")
        if volume < 0.0:
            raise ValueError("candle volume must be non-negative")
        if high_px < max(open_px, close_px, low_px):
            raise ValueError("candle high is below another price field")
        if low_px > min(open_px, close_px, high_px):
            raise ValueError("candle low is above another price field")
        out.append(row)
    return out


def _dataset_id(kind: str, symbol: str, granularity: int, rows: Sequence[Sequence[float]]) -> str:
    first = rows[0][0]
    last = rows[-1][0]
    return (
        f"{kind}:{symbol}:{int(granularity)}:"
        f"{first:.12g}:{last:.12g}:{len(rows)}"
    )


def snapshot_from_rows(
    rows: Sequence[Sequence[Any]],
    *,
    kind: str,
    symbol: str,
    granularity: int,
) -> dict[str, Any]:
    """Build a deterministic manifest from the exact logical rows to replay."""

    normalized = normalize_candle_rows(rows)
    if not normalized:
        raise ValueError("canonical replay snapshot cannot be empty")
    granularity = int(granularity)
    manifest_core = {
        "kind": str(kind),
        "symbol": str(symbol),
        "granularity": granularity,
        "row_count": len(normalized),
        "start_ts": normalized[0][0],
        "end_ts": normalized[-1][0],
        "rows_hash": stable_hash(normalized),
    }
    manifest = {
        **manifest_core,
        "dataset_id": _dataset_id(str(kind), str(symbol), granularity, normalized),
    }
    # Hash metadata and the exact normalized row hash together.  Parquet
    # container metadata is intentionally excluded: replay consumes logical
    # OHLCV values, not storage-format bytes.
    manifest["dataset_hash"] = stable_hash(manifest)
    return {"manifest": manifest, "rows": normalized}


def load_canonical_snapshot(
    *,
    kind: str = DATASET_KIND,
    symbol: str,
    granularity: int,
    start_ts: float | None = None,
    end_ts: float | None = None,
    window_bars: int | None = None,
) -> dict[str, Any]:
    """Load and freeze the exact feed-cache rows used by a historical replay."""

    rows = load_candles(kind, symbol, int(granularity))
    if start_ts is not None:
        floor = _finite_float(start_ts, name="start_ts")
        rows = [row for row in rows if float(row[0]) >= floor]
    if end_ts is not None:
        ceiling = _finite_float(end_ts, name="end_ts")
        rows = [row for row in rows if float(row[0]) <= ceiling]
    if window_bars is not None:
        window = int(window_bars)
        if window <= 0:
            raise ValueError("window_bars must be positive")
        rows = rows[-window:]
    return snapshot_from_rows(
        rows,
        kind=kind,
        symbol=symbol,
        granularity=int(granularity),
    )


def replay_trade_returns_rust(
    strategy_name: str,
    rows: Sequence[Sequence[Any]],
    *,
    warmup: int = 30,
    fee_bps: float = 0.0,
    max_hold_bars: int = 0,
    strategy_config: dict[str, Any] | None = None,
) -> list[float]:
    """Replay one strategy and return realized trade returns as decimals.

    Signal evaluation uses ``rust_core.run_strategy_opens_py`` on every bar and
    mirrors ``rust_core/src/backtest.rs`` entry/exit semantics.  The open series
    intentionally equals closes, matching ``strategy_engine._rust_backtest_strategy``.
    """

    if not strategy_name:
        raise ValueError("strategy_name is required")
    normalized_strategy_config = normalize_strategy_config(strategy_name, strategy_config)
    normalized = normalize_candle_rows(rows)
    warmup = int(warmup)
    max_hold_bars = int(max_hold_bars)
    fee_bps = _finite_float(fee_bps, name="fee_bps")
    if warmup < 0 or max_hold_bars < 0 or fee_bps < 0.0:
        raise ValueError("warmup, max_hold_bars and fee_bps must be non-negative")
    if len(normalized) < warmup + 10:
        return []

    rust_core = _require_rust_core()

    closes = [row[4] for row in normalized]
    opens = list(closes)  # matches strategy_engine._rust_backtest_strategy default
    volumes = [row[5] for row in normalized]
    highs = [row[2] for row in normalized]
    lows = [row[3] for row in normalized]

    open_trade: dict[str, Any] | None = None
    returns: list[float] = []

    def close_trade(trade: dict[str, Any], exit_price: float) -> float:
        if trade["side"] == "BUY":
            gross_pct = (exit_price - trade["entry_price"]) / trade["entry_price"] * 100.0
        else:
            gross_pct = (trade["entry_price"] - exit_price) / trade["entry_price"] * 100.0
        return_pct = gross_pct - (fee_bps / 100.0) * 2.0
        value = return_pct / 100.0
        if not math.isfinite(value):
            raise ValueError("canonical replay produced a non-finite trade return")
        return value

    for index in range(warmup, len(normalized)):
        if normalized_strategy_config:
            signal = rust_core.run_rsi_revert_opens_configured_py(
                closes[: index + 1],
                opens[: index + 1],
                volumes[: index + 1],
                highs[: index + 1],
                lows[: index + 1],
                period=normalized_strategy_config["period"],
                oversold=normalized_strategy_config["oversold"],
                overbought=normalized_strategy_config["overbought"],
            )
        else:
            signal = rust_core.run_strategy_opens_py(
                strategy_name,
                closes[: index + 1],
                opens[: index + 1],
                volumes[: index + 1],
                highs[: index + 1],
                lows[: index + 1],
            )
        if signal is None:
            continue
        action = signal[0]
        if action == "HOLD":
            continue
        if action not in {"BUY", "SELL"}:
            raise ValueError(f"canonical replay received unsupported action {action!r}")

        if open_trade is None:
            open_trade = {
                "entry_bar": index,
                "entry_price": closes[index],
                "side": action,
            }
            continue

        opposite = (
            (open_trade["side"] == "BUY" and action == "SELL")
            or (open_trade["side"] == "SELL" and action == "BUY")
        )
        held = index - int(open_trade["entry_bar"])
        forced = max_hold_bars > 0 and held >= max_hold_bars
        if opposite or forced:
            returns.append(close_trade(open_trade, closes[index]))
            open_trade = None

    if open_trade is not None:
        returns.append(close_trade(open_trade, closes[-1]))
    return returns


def _walk_forward_boundaries(
    n_rows: int,
    *,
    n_folds: int,
    purge_size: int,
    embargo_size: int,
):
    if n_folds < 2:
        raise ValueError("n_folds must be at least 2")
    if purge_size < 0 or embargo_size < 0:
        raise ValueError("purge_size and embargo_size must be non-negative")
    available = n_rows - purge_size - embargo_size
    fold_size = available // (n_folds + 1) if available > 0 else 0
    if fold_size < 40:
        raise ValueError("snapshot is too small for canonical walk-forward replay")
    boundaries = generate_walk_forward_splits(
        n_rows,
        train_size=fold_size,
        test_size=fold_size,
        step_size=fold_size,
        purge_size=purge_size,
        embargo_size=embargo_size,
        expanding=True,
    )[:n_folds]
    if len(boundaries) != n_folds:
        raise ValueError("snapshot cannot produce the requested walk-forward folds")
    return boundaries


def attest_snapshot_replay(
    snapshot: dict[str, Any],
    *,
    strategy_name: str,
    n_folds: int = 4,
    purge_size: int = 0,
    embargo_size: int = 0,
    warmup: int = 30,
    fee_bps: float = 0.0,
    max_hold_bars: int = 0,
    strategy_config: dict[str, Any] | None = None,
) -> tuple[list[list[float]], dict[str, Any]]:
    """Run leakage-safe OOS folds and return returns plus deterministic attestation."""

    if not isinstance(snapshot, dict) or not isinstance(snapshot.get("manifest"), dict):
        raise TypeError("snapshot must come from load_canonical_snapshot/snapshot_from_rows")
    normalized_strategy_config = normalize_strategy_config(strategy_name, strategy_config)
    rows = normalize_candle_rows(snapshot.get("rows", []))
    rebuilt = snapshot_from_rows(
        rows,
        kind=snapshot["manifest"]["kind"],
        symbol=snapshot["manifest"]["symbol"],
        granularity=int(snapshot["manifest"]["granularity"]),
    )
    if rebuilt["manifest"] != snapshot["manifest"]:
        raise ValueError("snapshot manifest does not match snapshot rows")

    boundaries = _walk_forward_boundaries(
        len(rows),
        n_folds=int(n_folds),
        purge_size=int(purge_size),
        embargo_size=int(embargo_size),
    )
    fold_returns: list[list[float]] = []
    fold_rows: list[dict[str, Any]] = []
    for boundary in boundaries:
        test_rows = rows[boundary.test_start:boundary.test_end]
        returns = replay_trade_returns_rust(
            strategy_name,
            test_rows,
            warmup=int(warmup),
            fee_bps=float(fee_bps),
            max_hold_bars=int(max_hold_bars),
            strategy_config=normalized_strategy_config,
        )
        fold_returns.append(returns)
        fold_rows.append({
            "fold": boundary.fold,
            "train_start": boundary.train_start,
            "train_end": boundary.train_end,
            "purge_start": boundary.purge_start,
            "purge_end": boundary.purge_end,
            "embargo_start": boundary.embargo_start,
            "embargo_end": boundary.embargo_end,
            "test_start": boundary.test_start,
            "test_end": boundary.test_end,
            "test_rows_hash": stable_hash(test_rows),
            "return_count": len(returns),
            "returns_hash": stable_hash(returns),
        })

    parameter_stability = None
    if normalized_strategy_config:
        parameter_stability = _build_parameter_stability_attestation(
            rows,
            boundaries,
            fold_returns,
            strategy_config=normalized_strategy_config,
            warmup=int(warmup),
            fee_bps=float(fee_bps),
            max_hold_bars=int(max_hold_bars),
        )

    core = {
        "schema_version": ATTESTATION_SCHEMA_VERSION,
        "attestation_type": ATTESTATION_TYPE,
        "runner": RUNNER_ID,
        "runner_source_sha256": _runner_source_sha256(),
        "dataset": snapshot["manifest"],
        "strategy_name": strategy_name,
        "strategy_config": normalized_strategy_config,
        "strategy_config_hash": stable_hash(normalized_strategy_config),
        "execution_config_bound": bool(normalized_strategy_config),
        "parameter_stability": parameter_stability,
        "warmup": int(warmup),
        "fee_bps": float(fee_bps),
        "max_hold_bars": int(max_hold_bars),
        "n_folds": int(n_folds),
        "purge_size": int(purge_size),
        "embargo_size": int(embargo_size),
        "folds": fold_rows,
        "fold_returns_hash": stable_hash(fold_returns),
    }
    attestation = {**core, "attestation_hash": stable_hash(core)}
    return fold_returns, attestation


def _basic_attestation_reasons(attestation: Any, fold_returns: Any) -> list[str]:
    reasons: list[str] = []
    if not isinstance(attestation, dict):
        return ["replay_attestation_missing"]
    required = {
        "schema_version", "attestation_type", "runner", "runner_source_sha256",
        "dataset", "strategy_name", "strategy_config", "strategy_config_hash",
        "execution_config_bound", "parameter_stability", "warmup", "fee_bps", "max_hold_bars",
        "n_folds", "purge_size", "embargo_size", "folds",
        "fold_returns_hash", "attestation_hash",
    }
    for name in sorted(required - set(attestation)):
        reasons.append(f"replay_attestation_missing_field:{name}")
    if reasons:
        return reasons
    if attestation["schema_version"] != ATTESTATION_SCHEMA_VERSION:
        reasons.append("replay_attestation_schema_mismatch")
    if attestation["attestation_type"] != ATTESTATION_TYPE or attestation["runner"] != RUNNER_ID:
        reasons.append("replay_attestation_runner_mismatch")
    try:
        normalized_config = normalize_strategy_config(
            attestation["strategy_name"], attestation["strategy_config"]
        )
        if normalized_config != attestation["strategy_config"]:
            reasons.append("replay_strategy_config_not_normalized")
        if stable_hash(normalized_config) != attestation["strategy_config_hash"]:
            reasons.append("replay_strategy_config_hash_mismatch")
        if bool(normalized_config) != (attestation["execution_config_bound"] is True):
            reasons.append("replay_execution_config_binding_mismatch")
        if normalized_config:
            reasons.extend(_parameter_stability_reasons(
                attestation["parameter_stability"],
                base_config=normalized_config,
                base_fold_returns=fold_returns,
            ))
        elif attestation["parameter_stability"] is not None:
            reasons.append("replay_unconfigured_parameter_stability_present")
    except (TypeError, ValueError, KeyError, OverflowError):
        reasons.append("replay_strategy_config_invalid")
    if attestation["runner_source_sha256"] != _runner_source_sha256():
        reasons.append("replay_runner_source_mismatch")
    core = dict(attestation)
    supplied_hash = core.pop("attestation_hash", None)
    try:
        if stable_hash(core) != supplied_hash:
            reasons.append("replay_attestation_hash_mismatch")
        if stable_hash(fold_returns) != attestation["fold_returns_hash"]:
            reasons.append("replay_fold_returns_hash_mismatch")
    except (TypeError, ValueError, OverflowError):
        reasons.append("replay_attestation_not_canonicalizable")
    folds = attestation.get("folds")
    if not isinstance(folds, list) or not isinstance(fold_returns, list) or len(folds) != len(fold_returns):
        reasons.append("replay_fold_count_mismatch")
    else:
        for index, (fold, returns) in enumerate(zip(folds, fold_returns)):
            if not isinstance(fold, dict):
                reasons.append(f"replay_fold_invalid:{index}")
                continue
            if fold.get("fold") != index:
                reasons.append(f"replay_fold_index_mismatch:{index}")
            if fold.get("return_count") != len(returns):
                reasons.append(f"replay_return_count_mismatch:{index}")
            try:
                if fold.get("returns_hash") != stable_hash(returns):
                    reasons.append(f"replay_returns_hash_mismatch:{index}")
            except (TypeError, ValueError, OverflowError):
                reasons.append(f"replay_returns_not_canonicalizable:{index}")
    return reasons


def verify_evidence_replay_binding(
    evidence: Any,
    *,
    reverify_source: bool = True,
) -> tuple[bool, list[str]]:
    """Verify that alpha evidence is bound to canonical feed-cache replay output.

    With ``reverify_source=True`` (the promotion-gate default), verification
    reloads the exact time-bounded dataset from the canonical feed cache and
    reruns every OOS fold through the Rust signal evaluator.  Missing data,
    missing Rust support, or any mismatch fails closed.
    """

    if not isinstance(evidence, dict):
        return False, ["evidence_not_object"]
    fold_returns = evidence.get("fold_returns")
    attestation = evidence.get("replay_attestation")
    reasons = _basic_attestation_reasons(attestation, fold_returns)
    if reasons:
        return False, list(dict.fromkeys(reasons))

    dataset = attestation.get("dataset", {})
    if evidence.get("dataset_id") != dataset.get("dataset_id"):
        reasons.append("replay_dataset_id_mismatch")
    if evidence.get("dataset_hash") != dataset.get("dataset_hash"):
        reasons.append("replay_dataset_hash_mismatch")

    if reverify_source and not reasons:
        try:
            snapshot = load_canonical_snapshot(
                kind=dataset["kind"],
                symbol=dataset["symbol"],
                granularity=int(dataset["granularity"]),
                start_ts=float(dataset["start_ts"]),
                end_ts=float(dataset["end_ts"]),
            )
            if snapshot["manifest"] != dataset:
                reasons.append("replay_dataset_source_mismatch")
            else:
                replay_returns, rebuilt_attestation = attest_snapshot_replay(
                    snapshot,
                    strategy_name=attestation["strategy_name"],
                    n_folds=int(attestation["n_folds"]),
                    purge_size=int(attestation["purge_size"]),
                    embargo_size=int(attestation["embargo_size"]),
                    warmup=int(attestation["warmup"]),
                    fee_bps=float(attestation["fee_bps"]),
                    max_hold_bars=int(attestation["max_hold_bars"]),
                    strategy_config=attestation["strategy_config"],
                )
                if replay_returns != fold_returns:
                    reasons.append("replay_regenerated_returns_mismatch")
                if rebuilt_attestation != attestation:
                    reasons.append("replay_regenerated_attestation_mismatch")
        except (ImportError, RuntimeError, TypeError, ValueError, KeyError, OverflowError):
            reasons.append("replay_source_reverification_failed")

    return not reasons, list(dict.fromkeys(reasons))


def bind_evidence_to_replay(
    evidence: dict[str, Any],
    attestation: dict[str, Any],
) -> dict[str, Any]:
    """Attach replay provenance and re-hash an otherwise valid alpha artifact."""

    valid, reasons = verify_alpha_validation_evidence(evidence)
    if not valid:
        raise ValueError("cannot bind invalid alpha evidence: " + ",".join(reasons))
    replay_reasons = _basic_attestation_reasons(attestation, evidence.get("fold_returns"))
    if evidence.get("dataset_id") != attestation.get("dataset", {}).get("dataset_id"):
        replay_reasons.append("replay_dataset_id_mismatch")
    if evidence.get("dataset_hash") != attestation.get("dataset", {}).get("dataset_hash"):
        replay_reasons.append("replay_dataset_hash_mismatch")
    if attestation.get("execution_config_bound") is True and evidence.get("candidate_config") != attestation.get("strategy_config"):
        replay_reasons.append("replay_candidate_execution_config_mismatch")
    if attestation.get("execution_config_bound") is True:
        stability = attestation.get("parameter_stability")
        if not isinstance(stability, dict) or evidence.get("parameter_stability_score") != stability.get("score"):
            replay_reasons.append("replay_parameter_stability_score_mismatch")
    if replay_reasons:
        raise ValueError("cannot bind mismatched replay: " + ",".join(replay_reasons))

    bound = dict(evidence)
    bound.pop("evidence_hash", None)
    bound["replay_attestation"] = attestation
    bound["replay_provenance_bound"] = True
    bound["evidence_hash"] = stable_hash(bound)
    valid, reasons = verify_alpha_validation_evidence(bound)
    if not valid:
        raise ValueError("bound evidence failed alpha verification: " + ",".join(reasons))
    return bound


def build_alpha_evidence_from_canonical_replay(
    *,
    candidate_id: str,
    candidate_source_sha: str,
    candidate_config: dict[str, Any],
    strategy_name: str,
    strategy_config: dict[str, Any] | None = None,
    symbol: str,
    granularity: int,
    net_pnl_after_cost_usd: float,
    cost_coverage_ratio: float,
    regimes_tested: Sequence[str],
    accounting_invariants_ok: bool,
    lineage_verified: bool,
    parameter_stability_score: float | None = None,
    start_ts: float | None = None,
    end_ts: float | None = None,
    window_bars: int | None = None,
    n_folds: int = 4,
    purge_size: int = 0,
    embargo_size: int = 0,
    warmup: int = 30,
    fee_bps: float = 0.0,
    max_hold_bars: int = 0,
    **alpha_kwargs: Any,
) -> dict[str, Any]:
    """End-to-end constructor: cache bytes -> Rust OOS returns -> alpha evidence."""

    normalized_strategy_config = normalize_strategy_config(strategy_name, strategy_config)
    if normalized_strategy_config and candidate_config != normalized_strategy_config:
        raise ValueError("candidate_config must equal the executable strategy_config")

    snapshot = load_canonical_snapshot(
        kind=DATASET_KIND,
        symbol=symbol,
        granularity=int(granularity),
        start_ts=start_ts,
        end_ts=end_ts,
        window_bars=window_bars,
    )
    fold_returns, attestation = attest_snapshot_replay(
        snapshot,
        strategy_name=strategy_name,
        n_folds=n_folds,
        purge_size=purge_size,
        embargo_size=embargo_size,
        warmup=warmup,
        fee_bps=fee_bps,
        max_hold_bars=max_hold_bars,
        strategy_config=normalized_strategy_config,
    )
    manifest = snapshot["manifest"]
    if normalized_strategy_config:
        stability = attestation.get("parameter_stability")
        if not isinstance(stability, dict):
            raise ValueError("configured canonical replay did not derive parameter stability")
        derived_stability_score = float(stability["score"])
        if parameter_stability_score is not None:
            supplied_stability = _finite_float(parameter_stability_score, name="parameter_stability_score")
            if supplied_stability != derived_stability_score:
                raise ValueError("caller parameter_stability_score does not match replay-derived stability")
    else:
        if parameter_stability_score is None:
            raise ValueError("parameter_stability_score remains required for unconfigured research replay")
        derived_stability_score = _finite_float(parameter_stability_score, name="parameter_stability_score")

    evidence = build_alpha_validation_evidence(
        candidate_id=candidate_id,
        candidate_source_sha=candidate_source_sha,
        candidate_config=candidate_config,
        dataset_id=manifest["dataset_id"],
        dataset_hash=manifest["dataset_hash"],
        fold_returns=fold_returns,
        net_pnl_after_cost_usd=net_pnl_after_cost_usd,
        cost_coverage_ratio=cost_coverage_ratio,
        regimes_tested=regimes_tested,
        accounting_invariants_ok=accounting_invariants_ok,
        lineage_verified=lineage_verified,
        parameter_stability_score=derived_stability_score,
        **alpha_kwargs,
    )
    return bind_evidence_to_replay(evidence, attestation)
